language: python
python:
  - "3.5"
env:
  - NETX=1.11
  - NETX=true
install:
  - if [ $NETX = 1.11 ] ; then echo 'installing networkx 1.11' ; pip install networkx==1.11 ; fi
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source ndex2 setup.py test

after_success: coveralls
