language: python
dist: focal
python:
  - "3.6"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
env:
  - NETX=1.11
  - NETX=true
jobs:
  exclude:
    - python: "3.8"
      env: NETX=1.11
    - python: "3.9"
      env: NETX=1.11
    - python: "3.10"
      env: NETX=1.11
    - python: "3.11"
      env: NETX=1.11
    - python: "3.12"
      env: NETX=1.11

install:
  - if [ $NETX = 1.11 ] ; then echo 'installing networkx 1.11' ; pip install networkx==1.11 ; fi
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install coveralls
script:
  - coverage run --source ndex2 -m unittest discover

after_success: coveralls
